using System;
using System.Collections.Generic;

namespace Fiken.Net
{
    public class FikenInvoice
    {
        /// <summary>
        /// Self Url
        /// </summary>
        public Uri Url { get; set; }

        /// <summary>
        /// Unique invoice number generated by Fiken
        /// </summary>
        public int? InvoiceNumber { get; set; }

        /// <summary>
        /// Unique KID number for customers with a KID/OCR agreement
        /// </summary>
        public string Kid { get; set; }

        /// <summary>
        /// Net amount in øre
        /// </summary>
        public int Net { get; set; }

        /// <summary>
        /// VAT (MVA) amount in øre
        /// </summary>
        public int Vat { get; set; }

        /// <summary>
        /// Gross amount (=net + vat) in øre
        /// </summary>
        public int Gross { get; set; }

        /// <summary>
        /// Comment/description printed above the invoice lines
        /// </summary>
        public string Comment { get; set; }

        /// <summary>
        /// Your reference
        /// </summary>
        public string YourReference { get; set; }

        /// <summary>
        ///  Our reference
        /// </summary>
        public string OurReference { get; set; }

        /// <summary>
        /// [REQUIRED] The customer link for this invoice
        /// </summary>
        public Uri Customer { get; set; }

        /// <summary>
        /// [REQUIRED] The bank account url
        /// </summary>
        public Uri BankAccountUrl { get; set; }

        /// <summary>
        /// [REQUIRED] Invoice date
        /// </summary>
        public DateTime IssueDate { get; set; }
        
        /// <summary>
        /// [REQUIRED] Due date
        /// </summary>
        public DateTime DueDate { get; set; }

        /// <summary>
        /// The address printed on the invoice
        /// </summary>
        public FikenAddress Address { get; set; }

        /// <summary>
        /// Invoice lines
        /// </summary>
        public IEnumerable<FikenInvoiceLine> Lines { get; set; }
    }
}
